In [1]:
from pandas import Series, DataFrame
import pandas as pd

In [2]:
myCampus = Series([200, 300, 300, 400, 500])
myCampus

0    200
1    300
2    300
3    400
4    500
dtype: int64

In [3]:
myCampus = Series([200, 300, 300, 400, 500], 
        index=['2023-07-25', '2023-07-26', '2023-07-27', '2023-07-28', '2023-07-29'])
myCampus

2023-07-25    200
2023-07-26    300
2023-07-27    300
2023-07-28    400
2023-07-29    500
dtype: int64

In [4]:
myCampus['2023-07-26']

300

In [7]:
data = {'foreigner': [1, 2, 3, 4, 5, 6], 
        'sratio': [10, 20, 30, 40, 50, 60], 
        'org': [100, 200, 300, 400, 500, 600],
        'sprice': [1, 2, 3, 4, 5, 6],
        'private':[10, 20, 30, 40, 50, 60]}
data

{'foreigner': [1, 2, 3, 4, 5, 6],
 'sratio': [10, 20, 30, 40, 50, 60],
 'org': [100, 200, 300, 400, 500, 600],
 'sprice': [1, 2, 3, 4, 5, 6],
 'private': [10, 20, 30, 40, 50, 60]}

In [ ]:
dates=['2023-07-25', '2023-07-26', '2023-07-27', '2023-07-28', '2023-07-29']

In [8]:
frame = DataFrame(data, 
                  columns=['private', 'org', 'foreigner', 'sratio', 'sprice'], 
                  index=['2023-07-25', '2023-07-26', '2023-07-27', '2023-07-28', '2023-07-29', '2023-07-30'])
frame

            private  org  foreigner  sratio  sprice
2023-07-25       10  100          1      10       1
2023-07-26       20  200          2      20       2
2023-07-27       30  300          3      30       3
2023-07-28       40  400          4      40       4
2023-07-29       50  500          5      50       5
2023-07-30       60  600          6      60       6

In [9]:
frame['foreigner']

2023-07-25    1
2023-07-26    2
2023-07-27    3
2023-07-28    4
2023-07-29    5
2023-07-30    6
Name: foreigner, dtype: int64

In [10]:
frame['org']

2023-07-25    100
2023-07-26    200
2023-07-27    300
2023-07-28    400
2023-07-29    500
2023-07-30    600
Name: org, dtype: int64

In [11]:
frame.T

,2023-07-25,2023-07-26,2023-07-27,2023-07-28,2023-07-29,2023-07-30
private,10,20,30,40,50,60
org,100,200,300,400,500,600
foreigner,1,2,3,4,5,6
sratio,10,20,30,40,50,60
sprice,1,2,3,4,5,6

In [12]:
!pwd

/home/a7062c47-8896-45dc-9f07-9aecfa0df1bc/my-code

In [13]:
import inspect

In [14]:
import random

In [15]:
inspect.getfile(random)

'/opt/conda/envs/anaconda-panel-2023.05-py310/lib/python3.11/random.py'

In [16]:
!pip list

Package                       Version
----------------------------- ---------------
aiobotocore                   2.5.0
aiofiles                      22.1.0
aiohttp                       3.8.3
aioitertools                  0.7.1
aiosignal                     1.2.0
aiosqlite                     0.18.0
alabaster                     0.7.12
altair                        5.0.1
anaconda-catalogs             0.2.0
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
asciitree                     0.3.3
astroid                       2.14.2
astropy                       5.1
asttokens                     2.0.5
async-timeout                 4.0.2
atomicwrites                  1.4.0
attrs                         22.1.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.11.0
backcall                      0.2.0
bcrypt                        3.2.0
beautifulsoup4                4.12.2
binaryornot                   0.4.4
black                         0.0
bleach                        4.1.0
bokeh                         3.1.1
botocore                      1.29.76
Bottleneck                    1.3.5
brotlipy                      0.7.0
certifi                       2023.5.7
cffi                          1.15.1
cftime                        1.6.2
chardet                       4.0.0
charset-normalizer            2.0.4
click                         8.0.4
cloudpickle                   2.2.1
colorama                      0.4.6
colorcet                      3.0.1
comm                          0.1.2
constantly                    15.1.0
contourpy                     1.0.5
cookiecutter                  1.7.3
cramjam                       2.6.2
cryptography                  39.0.1
cssselect                     1.1.0
cycler                        0.11.0
cytoolz                       0.12.0
daal4py                       2023.1.1
dask                          2023.6.0
datasets                      2.12.0
datashader                    0.15.0
datashape                     0.5.4
debugpy                       1.5.1
decorator                     5.1.1
defusedxml                    0.7.1
diff-match-patch              20200713
dill                          0.3.6
distributed                   2023.6.0
docstring-to-markdown         0.11
docutils                      0.18.1
entrypoints                   0.4
et-xmlfile                    1.1.0
executing                     0.8.3
fasteners                     0.16.3
fastjsonschema                2.16.2
fastparquet                   2023.4.0
filelock                      3.9.0
flake8                        6.0.0
Flask                         2.2.2
fonttools                     4.25.0
frozenlist                    1.3.3
fsspec                        2023.4.0
gensim                        4.3.0
gmpy2                         2.1.2
greenlet                      2.0.1
h5py                          3.7.0
HeapDict                      1.0.1
holoviews                     1.16.2
huggingface-hub               0.15.1
hvplot                        0.8.4
hyperlink                     21.0.0
idna                          3.4
imagecodecs                   2021.8.26
imageio                       2.31.1
imagesize                     1.4.1
imbalanced-learn              0.10.1
importlib-metadata            6.0.0
incremental                   21.3.0
inflection                    0.5.1
iniconfig                     1.1.1
intake                        0.6.8
intake-parquet                0.2.3
intake-xarray                 0.6.1
intervaltree                  3.1.0
ipykernel                     6.19.2
ipython                       8.12.0
ipython-genutils              0.2.0
ipywidgets                    8.0.4
isort                         5.9.3
itemadapter                   0.3.0
itemloaders                   1.0.4
itsdangerous                  2.0.1
jaraco.classes                3.2.1
jedi                          0.18.1
jeepney                       0.7.1
jellyfish                     0.9.0
Jinja2                        3.1.2
jinja2-time                   0.2.0
jmespath                      0.10.0
joblib                        1.2.0
json5                         0.9.6
jsonschema                    4.17.3
jupyter                       1.0.0
jupyter_client                8.1.0
jupyter-console               6.6.3
jupyter_core                  5.3.0
jupyter-events                0.6.3
jupyter_server                2.5.0
jupyter_server_fileid         0.9.0
jupyter_server_terminals      0.4.4
jupyter_server_ydoc           0.8.0
jupyter-ydoc                  0.2.4
jupyterlab                    3.6.3
jupyterlab-pygments           0.1.2
jupyterlab_server             2.22.0
jupyterlab-widgets            3.0.5
keyring                       23.13.1
kiwisolver                    1.4.4
lazy_loader                   0.2
lazy-object-proxy             1.6.0
linkify-it-py                 2.0.0
llvmlite                      0.40.0
lmdb                          1.4.1
locket                        1.0.0
lxml                          4.9.1
lz4                           4.3.2
Markdown                      3.4.1
markdown-it-py                2.2.0
MarkupSafe                    2.1.1
matplotlib                    3.7.1
matplotlib-inline             0.1.6
mccabe                        0.7.0
mdit-py-plugins               0.3.0
mdurl                         0.1.0
mistune                       0.8.4
mkl-service                   2.4.0
more-itertools                8.12.0
mpmath                        1.2.1
msgpack                       1.0.3
multidict                     6.0.2
multipledispatch              0.6.0
multiprocess                  0.70.14
munkres                       1.1.4
mypy-extensions               0.4.3
nbclassic                     0.5.5
nbclient                      0.5.13
nbconvert                     6.5.4
nbformat                      5.7.0
nest-asyncio                  1.5.6
netCDF4                       1.6.2
networkx                      2.8.4
nltk                          3.8.1
notebook                      6.5.4
notebook_shim                 0.2.2
numba                         0.57.0
numcodecs                     0.11.0
numexpr                       2.8.4
numpy                         1.24.3
numpydoc                      1.5.0
openpyxl                      3.0.10
packaging                     23.0
pandas                        1.5.3
pandocfilters                 1.5.0
panel                         1.0.4
param                         1.13.0
parsel                        1.6.0
parso                         0.8.3
partd                         1.2.0
pathspec                      0.10.3
patsy                         0.5.3
pep8                          1.7.1
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.4.0
pip                           23.1.2
platformdirs                  2.5.2
plotly                        5.9.0
pluggy                        1.0.0
ply                           3.11
pooch                         1.4.0
poyo                          0.5.0
prometheus-client             0.14.1
prompt-toolkit                3.0.36
Protego                       0.1.16
psutil                        5.9.0
ptyprocess                    0.7.0
pure-eval                     0.2.2
py-cpuinfo                    8.0.0
pyarrow                       11.0.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycodestyle                   2.10.0
pycparser                     2.21
pyct                          0.5.0
pycurl                        7.45.2
PyDispatcher                  2.0.5
pydocstyle                    6.3.0
pyerfa                        2.0.0
pyflakes                      3.0.1
Pygments                      2.15.1
pylint                        2.16.2
pylint-venv                   2.3.0
pyls-spyder                   0.4.0
pyodbc                        4.0.34
pyOpenSSL                     23.0.0
pyparsing                     3.0.9
PyQt5-sip                     12.11.0
pyrsistent                    0.18.0
PySocks                       1.7.1
pytest                        7.3.1
python-dateutil               2.8.2
python-json-logger            2.0.7
python-lsp-black              1.2.1
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.7.2
python-slugify                5.0.2
python-snappy                 0.6.1
pytoolconfig                  1.2.5
pytz                          2022.7
pyviz-comms                   2.3.0
PyWavelets                    1.4.1
pyxdg                         0.27
PyYAML                        6.0
pyzmq                         25.1.0
QDarkStyle                    3.0.2
qstylizer                     0.2.2
QtAwesome                     1.2.2
qtconsole                     5.4.2
QtPy                          2.2.0
queuelib                      1.5.0
regex                         2022.7.9
requests                      2.29.0
requests-file                 1.5.1
responses                     0.13.3
rfc3339-validator             0.1.4
rfc3986-validator             0.1.1
rope                          1.7.0
Rtree                         1.0.1
s3fs                          2023.4.0
sacremoses                    0.0.43
scikit-image                  0.20.0
scikit-learn                  1.2.2
scikit-learn-intelex          20230426.111612
scipy                         1.10.1
Scrapy                        2.8.0
seaborn                       0.12.2
SecretStorage                 3.3.1
Send2Trash                    1.8.0
service-identity              18.1.0
setuptools                    67.8.0
sip                           6.6.2
six                           1.16.0
smart-open                    5.2.1
sniffio                       1.2.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.4
Sphinx                        5.0.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.4.3
spyder-kernels                2.4.3
SQLAlchemy                    1.4.39
stack-data                    0.2.0
statsmodels                   0.13.5
sympy                         1.11.1
tables                        3.8.0
tabulate                      0.8.10
TBB                           0.2
tblib                         1.7.0
tenacity                      8.2.2
terminado                     0.17.1
text-unidecode                1.3
textdistance                  4.2.1
threadpoolctl                 2.2.0
three-merge                   0.1.1
tifffile                      2021.7.2
tinycss2                      1.2.1
tldextract                    3.2.0
tokenizers                    0.13.2
toml                          0.10.2
tomli                         2.0.1
tomlkit                       0.11.1
toolz                         0.12.0
torch                         2.0.1
tornado                       6.2
tqdm                          4.65.0
traitlets                     5.7.1
transformers                  4.29.2
Twisted                       22.10.0
typing_extensions             4.6.3
uc-micro-py                   1.0.1
ujson                         5.4.0
Unidecode                     1.2.0
urllib3                       1.26.16
w3lib                         1.21.0
watchdog                      2.1.6
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              0.58.0
Werkzeug                      2.2.3
whatthepatch                  1.0.2
wheel                         0.38.4
widgetsnbextension            4.0.5
wrapt                         1.14.1
wurlitzer                     3.0.2
xarray                        2022.11.0
xxhash                        2.0.2
xyzservices                   2022.9.0
y-py                          0.5.9
yapf                          0.31.0
yarl                          1.8.1
ypy-websocket                 0.8.2
zarr                          2.13.3
zict                          2.2.0
zipp                          3.11.0
zope.interface                5.4.0

In [17]:
frame1 = pd.read_csv('ex1.csv')
frame1

   id       name   price           description
0   1     iphone  890000      iphone 6s 7 8 x
1   2    android  990000         samsung phone
2   3   winphone  450000   microsoft winphone

In [18]:
!ls

Untitled.ipynb	ex1.csv

In [19]:
result = pd.read_table('ex3.csv', sep='\s+')
result

   data1  data2  data3
0    1.2    2.3    1.3
1    0.1    1.5    2.5
2    3.1    3.2    3.3

In [20]:
frame2 = pd.read_csv('ex2.csv', names=['id', 'name', 'price', 'desc'])
frame2

   id       name   price                  desc
0   1     iphone  890000      iphone 6s 7 8 x
1   2    android  990000         samsung phone
2   3   winphone  450000   microsoft winphone

In [21]:
dfExcel = pd.read_excel('demo.xlsx', 'Sheet1')
dfExcel

     사번 성별  나이  판매금액   수입
0  E001  M  34   123  350
1  E002  F  40   114  450
2  E003  F  37   135  169
3  E004  M  30   139  189
4  E005  F  44   117  183
5  E006  M  36   121   90
6  E007  M  32   133  166
7  E008  F  26   140  120
8  E009  M  32   133   75
9  E010  M  36   133   40

In [22]:
import pandas as pd

# 엑셀 파일 읽기
df = pd.read_excel('전자제품_판매관리.xlsx')

# 데이터 출력
print(df)

         Date                     Name Prod_ID   Price  Quantity    Total
0  2023-01-27       trip modern recent  Prod_8  227.83         3   683.49
1  2023-12-03     common strategy find  Prod_8  636.43         2  1272.86
2  2023-11-12   quickly production arm  Prod_9  438.96         4  1755.84
3  2023-06-01    business decide clear  Prod_6  995.41         6  5972.46
4  2023-05-12  whom picture generation  Prod_7  128.34         4   513.36
..        ...                      ...     ...     ...       ...      ...
95 2023-11-09       range purpose this  Prod_3  292.29         6  1753.74
96 2023-01-02             baby ten way  Prod_4  699.77         6  4198.62
97 2023-04-24      natural fact change  Prod_2  842.13         1   842.13
98 2023-09-13     heavy impact involve  Prod_6  396.81         8  3174.48
99 2023-09-07          sound soon upon  Prod_4  395.21         2   790.42

[100 rows x 6 columns]